name: GitHub Actions Demo

on: 
  push:
    branches: main
    paths-ignore: .github
  pull_request:
    branches: main
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
jobs:
  Build:
    runs-on: unbuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo ${{ github.head_ref || github.ref_name }} 
      - run: |
          echo "::set-output name=FILELIST::$(find . -name '*' -print)"
  
